### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Requests_Hooks' not found in phar://....

### ISSUE THREAD

**Issue by MoOx** [wp-cli/restful#116]
I am trying to use wp-cli to download wordpress export file.
I did the following

```
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
php wp-cli.phar --info
chmod +x wp-cli.phar
sudo mv wp-cli.phar /usr/local/bin/wp
php -d memory_limit=512M wp package install wp-cli/restful
wp export --http=https://my-host
```

and just got

```

Fatal error: Uncaught Error: Class 'Requests_Hooks' not found in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php:568
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php(363): Requests::set_defaults('http://dame.bio', Array, NULL, 'HEAD', Array)
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(623): Requests::request('http://dame.bio', Array, NULL, 'HEAD', Array)
#2 /~/.wp-cli/packages/vendor/wp-cli/restful/inc/Runner.php(94): WP_CLI\Utils\http_request('HEAD', 'http://dame.bio')
#3 /~/.wp-cli/packages/vendor/wp-cli/restful/inc/Runner.php(22): WP_REST_CLI\Runner::auto_discover_api('http://dame.bio')
#4 /~/.wp-cli/packages/vendor/wp-cli/restful/wp-rest-cli.php(10): WP_REST_CLI\Runner::load_remote_commands()
#5 /~/.wp-cli/packages/vendor/composer/autoload_real.php(66): require('/~/.wp...')
#6 /~/.wp-cli/packages/vendor/composer/autoload_real.php(56): composerRequire86500668dbb2581e1c0704f41a37ea4e('22bd962 in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php on line 568
```

**Comment by MoOx** [comment]
FYI

```
❯ wp --info
OS:	Darwin 18.5.0 Darwin Kernel Version 18.5.0: Wed Jan 16 00:04:52 PST 2019; root:xnu-4903.250.305~71/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/bin/php
PHP version:	7.1.23
php.ini used:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/moox
WP-CLI packages dir:	/Users/moox/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.1.0
```

**Comment by Moumoutaru** [comment]
Seeing  this as well.

**Comment by matlantis** [comment]
run into the same issue

`» wp --info                                                                  19-05-06 7:52:14
OS:	Linux 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/bin/php7.2
PHP version:	7.2.17-0ubuntu0.18.04.1
php.ini used:	/etc/php/7.2/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/martin/.wp-cli/packages/cache/repo/https---wp-cli.org-package-index
WP-CLI packages dir:	/home/martin/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.2.0`

**Comment by dennisschuerholz** [comment]
I run into the same problem on two different systems and trying different php and wp-cli versions.
`» wp --info
OS:     Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64
Shell:  /usr/bin/zsh
PHP binary:     /usr/bin/php5
PHP version:    5.6.30-0+deb8u1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.2.0`
`» wp --info
OS:	Linux 4.19.42-1-MANJARO #1 SMP PREEMPT Fri May 10 20:52:43 UTC 2019 x86_64
Shell:	/usr/bin/zsh
PHP binary:	/usr/bin/php
PHP version:	7.3.5
php.ini used:	/etc/php/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/dennis
WP-CLI packages dir:	/home/dennis/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.3.0-alpha-b0be5c1`

**Comment by svetozarsadecky** [comment]
Same issue 

```⇒  wp --info
OS:	Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php@7.1/7.1.20/bin/php
PHP version:	7.1.20
php.ini used:	/usr/local/etc/php/7.1/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/daimonis
WP-CLI packages dir:	/Users/daimonis/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.3.0-alpha-49f183b```

**Comment by hilt86** [comment]
any updates on this? surely there are more than 5 people using wp-cli's restful features in the world!

**Comment by hilt86** [comment]
@schlessera is this a packaging issue or something we can have a work-around for?

**Comment by schlessera** [comment]
I assume the Restful package needs to be updated to use the latest version of the `rmccue/requests` dependency. Let me check that.

**Comment by schlessera** [comment]
Alright, I found out what the problem is. For requests done `wp-cli/restful`, WordPress Core is not loaded, so the logic to prepare the Requests library that WordPress Core has is not processed either; the autoloader is simply missing in that case.

This needs to be fixed in the `wp-cli/wp-cli` package's `Utils\http_request()` function, so moving the issue over there.
